config/routes.rb
Rails.application.routes.draw do




  devise_for :users
  resources :users
  resources :posts do

    resources :messages, except: [:show, :index]
end

    root to: 'posts#index'
  end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :messages
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     	has_many :posts
     	has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_post
  before_action :authenticate_user!

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.post_id = @post.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to @post, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end
    def set_post
      @post = Post.find(params[:post_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :description, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @messages = Message.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @messages = Message.all
    @message = Message.find_by(post_id: params[:id])
    @post_comments = @post.messages.all
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :price, :bedrooms, :area).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	# after_action :verify_authorized



	def index
		@users = User.all
		# authorize User
	end

	def show
		@user = User.find(params[:id])
		# authorize @user
	end

	def update
		@user = User.find(params[:id])
		
		# authorize @user
		if @user.update_attributes(secure_params)
			redirect_to users_path, :notice => "User updated."
		else
			redirect_to users_path, :alert => "Unable to update user."
		end
	end

	def destroy
		user = User.find(params[:id])
		# authorize user
		user.destroy
		redirect_to users_path, :notice => "User deleted."
	end

	private

	def secure_params
		params.require(:user).permit(:role, :name)
	end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_navbar.html.erb
<%# add navigation links to this file %>
	<% if user_signed_in? %>
    <li><%= link_to new_post_path do %>
          <i class="glyphicon glyphicon-plus"></i> New Post
      <% end %>
    </li>
	  <li><%= link_to 'Profile', users_path(current_user) %></li>
	  <li><%= link_to 'Posts', posts_path %></li>
	  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
	<% else %>
	  <li><%= link_to 'Sign up', new_user_registration_path %></li>
	  <li><%= link_to 'Already a member?', new_user_session_path %></li>
	<% end %>
	

app/views/layouts/_navigation.html.erb
Signed in as <%= current_user.email %>. This is not you?
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top" id="nav_bar">
  <div class="container-fluid">
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand" >
        <li style="list-style:none;"><%= link_to_unless_current("Realtor", root_path) %></li>
      </div>
    </div>
    <div class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navbar' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_searchbox.html.erb
<% if user_signed_in? %> 
	<header>
		
	</header>
	<% if user_signed_in? %>
	  <li><%= link_to 'Posts', posts_path %></li>
	<% end %>
<% end %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
    <% if user_signed_in? %>

      <%= render 'layouts/navigation' %>
      <%= render 'layouts/searchbox' %>
      <% else %>
      <%= render 'visitors/index' %>
    <% end %>

</div>
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/navigation.html.erb
       
        <h1> Signed in as <%= current_user.email %>. This is not you?</h1>

app/views/messages/_form.html.erb
<%= form_for([@post, @message]) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/posts/_form.html.erb
<div class="container" style="margin-top:-50px;">
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form>
      <h1>Create a post!</h1>
      <div class="form-group">
        <label><%= f.label :title %></label>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label><%= f.label :price %></label>
        <%= f.number_field :price, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label><%= f.label :bedrooms %></label>
        <%= f.number_field :bedrooms, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label><%= f.label :area %></label>
        <%= f.text_field :area, class: 'form-control' %>
      </div>
      <div class="form-group">
          <%= f.submit :class => "btn btn-primary btn-lg" %>
      </div>
    </form>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%= button_to "delete", @post, :method=>:delete, :class=>:destroy %>

app/views/posts/index.html.erb
<div class="container" style="margin-top:70px;">
  <% @posts.each do |post| %>
      <div class="col-sm-12 col-md-6 col-lg-4" >
        <div class="thumbnail">
            <img src="assets/pic1.png" alt="...">
            <p>Title:<%= post.title %></p>
            <p>Price:<%= post.price %></p>
            <p>Area:<%= post.area %></p>
            <p>
              <%= link_to "Show", post, :class => "btn btn-primary btn-lg" %>
          </p>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<header>

<%= render 'form' %>
</header>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container" style="margin-top:80px;">
	<div class="row" >
		<div class="col-sm-12 col-md-4 col-lg-4" style="text-align:center;">
			<h1>Post Page | <%= @post.id %> | </h1>
			<p id="notice"><%= notice %></p>
			<p>
			  <strong>Title:</strong>
			  <%= @post.title %>
			</p>
			<p>
			  <strong>Price:</strong>
			  <%= @post.price %>
			</p>
			<p>
			  <strong>Bedrooms:</strong>
			  <%= @post.bedrooms %>
			</p>
			<p>
			  <strong>Area:</strong>
			  <%= @post.area %>
			</p>
			<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary btn-lg' %>
			<%= link_to 'Back', posts_path, class: 'btn btn-primary btn-lg' %>
		</div>
		<div class="col-sm-12 col-md-8 col-lg-8" style="text-align:center;">
			<h1>Comments:</h1>

			<hr>
				<%= link_to "New Message", new_post_message_path(@post) %>
				<hr>


				<% if @messages.blank? %>
					<h3>No comments yet, be the first!</h3>
				<% else %>
					<% @messages.each do |message| %>
						<div class="thumbnail" >
							<h3>Title: | <%= message.title %></h3>
							<h3>Description: | <%= message.description %></h3>
							<h3>User Id: | <%= message.user_id %> | Post Id: | <%= message.post_id %> | </h3>
						</div>
						<hr>
					<% end %>
				<% end %>
  		</div>
<br>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<br>
<br>
<br>
<h1>Profile page</h1>

app/views/visitors/_index.html.erb
<html lang="en">
<body id="page-top" class="index">

    <!-- Header -->
    <header style="background:#18bc9c;color:white;text-align:center;margin-top:-50px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name">Welcome to Realtor</span>
                        <hr class="star-light">
                        <span class="skills">A place where you can sell or buy houses without having to do any work!</span>
                        <br>
                        <br>
                        <%= link_to "Create Account!", new_user_registration_path, :class => "btn btn-primary btn-lg" %>
                        <%= link_to "Already a member?", new_user_session_path, :class => "btn btn-primary btn-lg" %>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Portfolio Grid Section -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Our Team</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 portfolio-item">
                    <div class="thumbnail">
                        <img src="assets/pic1.png" alt="...">
                        <div class="caption">
                            <h3>Brandon Smith</h3>
                            <p>Founder</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 portfolio-item">
                    <div class="thumbnail">
                        <img src="assets/pic1.png" alt="...">
                        <div class="caption">
                            <h3>Dominic Nunes</h3>
                            <p>Co-Founder</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>This website is desgined for easy navigation and the ability to sell/buy houses.Realtor helps you sell or buy any kind of building without having to do any reserach</p>
                </div>
                <div class="col-lg-4">
                    <p>Whether you're a student looking to for a place, a parent looking to sell their place, or a realestate agent who is looking for more clients. </p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <a href="#" class="btn btn-lg btn-outline">
                        View more!
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact Me</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Email Address</label>
                                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Message</label>
                                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-lg">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visble-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
</body>
</html>

<!-- <p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p> -->